name: Generate UI for toy_shop project

on: [push, delete]

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}/getting_started/toy_shop
  RE_DATA_CONFIG_DIR: ${{ github.workspace }}/getting_started/toy_shop
  RE_DATA_TESTING_USER: ${{ secrets.RE_DATA_TESTING_USER }}
  RE_DATA_TESTING_PASSWORD: ${{ secrets.RE_DATA_TESTING_PASSWORD }}
  RE_DATA_SEND_ANONYMOUS_USAGE_STATS: 0

jobs:
  generate-ui:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Configure re_data.yml
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.notifications.slack.webhook_url = "${{secrets.RE_DATA_TESTING_SLACK_ALERTS_WEBHOOK}}"' ./getting_started/toy_shop/re_data.yml 
            yq -i '.notifications.email.smtp_password = "${{secrets.RE_DATA_SENDGRID_API_KEY}}"' ./getting_started/toy_shop/re_data.yml


      - name: Install re_data and python dependencies
        working-directory: .
        run: |
          pip install -e .
          pip install dbt-postgres==1.6.0

      - name: Install dbt dependencies
        working-directory: ./getting_started/toy_shop
        run: |
          dbt --version
          dbt deps

      - name: Initialize data and compute metrics
        working-directory: ./getting_started/toy_shop
        shell: bash
        run: |
          chmod +x ./setup_toy_shop.sh
          ./setup_toy_shop.sh toy_shop_postgres

      - name: Send alert notifications to various channels
        working-directory: ./getting_started/toy_shop
        if: github.repository == 're-data/re-data'
        run: |
          re_data notify slack --start-date 2021-01-01 --end-date 2021-01-11 --profiles-dir ${{env.DBT_PROFILES_DIR}} --project-dir ./ \
          --profile toy_shop_postgres --webhook-url ${{secrets.RE_DATA_TESTING_SLACK_ALERTS_WEBHOOK}} --subtitle="<https://github.com/${{ github.repository }}/commit/${{ github.sha }} |View Commit> - (postgres)"

      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"

      - name: Set homepage in package.json
        working-directory: ./re_data_ui
        run: contents=$(jq '.homepage="https://${{env.GITHUB_REPOSITORY_OWNER_PART_SLUG}}.github.io/${{env.GITHUB_REPOSITORY_NAME_PART_SLUG}}/ui-${{env.GITHUB_REF_SLUG}}"' package.json) && echo "${contents}" > package.json
        shell: bash

      - name: Install dependencies
        working-directory: ./re_data_ui
        run: |
          npm install

      - name: Build app for production
        working-directory: ./re_data_ui
        shell: bash
        run: ./build.sh
        env:
          PUBLIC_URL: https://${{env.GITHUB_REPOSITORY_OWNER_PART_SLUG}}.github.io/${{env.GITHUB_REPOSITORY_NAME_PART_SLUG}}/ui-${{env.GITHUB_REF_SLUG}}

      - name: Generate re_data artefacts
        working-directory: ./getting_started/toy_shop
        run: |
          re_data overview generate --start-date 2021-01-01 --profiles-dir ${{env.DBT_PROFILES_DIR}} --project-dir ./ --profile toy_shop_postgres

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./getting_started/toy_shop/target/re_data
          destination_dir: ./ui-${{env.GITHUB_REF_SLUG}}

  clean-up-deployment:
    runs-on: ubuntu-latest
    if: github.event_name == 'delete'
    
    steps:        
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Delete generated documentation and observability UI for branch
        run: |
          ls
          rm -rf ${{env.GITHUB_EVENT_REF_SLUG}}
          rm -rf ui-${{env.GITHUB_EVENT_REF_SLUG}}

      - name: Update github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
          keep_files: true
          # allow_empty_commit: true
